In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from data_preparation_pcg import prepare_dataset

# Data Preparation

In [2]:

class_name = 'Occupancy' #quello che vogliamo predirre

df = pd.read_csv('/Users/piyush2017/Code/2020_Data_Mining_Project_02/data_mining_2020_project_occupancy_detection/data/datatrainingcopy.csv', skipinitialspace=True, na_values='?', keep_default_na=True, parse_dates=True)
columns2remove = ['Number'] #eliminiamo perchè non ci servono
df.drop(columns2remove, inplace=True, axis=1)
df.head()

,date,Temperature,Humidity,Light,CO2,HumidityRatio,Occupancy
0,2/4/15 17:51,23.18,27.2720,426.0,721.25,0.004793,1
1,2/4/15 17:51,23.15,27.2675,429.5,714.00,0.004783,1
2,2/4/15 17:53,23.15,27.2450,426.0,713.50,0.004779,1
3,2/4/15 17:54,23.15,27.2000,426.0,708.25,0.004772,1
4,2/4/15 17:55,23.10,27.2000,426.0,704.50,0.004757,1

In [3]:
res = prepare_dataset(df, class_name)
df, feature_names, class_values, numeric_columns, rdf, real_feature_names, features_map = res
df.head()

   Temperature  Humidity  Light     CO2  HumidityRatio  Occupancy  Week_day
0        23.18   27.2720  426.0  721.25       0.004793          1         1
1        23.15   27.2675  429.5  714.00       0.004783          1         1
2        23.15   27.2450  426.0  713.50       0.004779          1         1
3        23.15   27.2000  426.0  708.25       0.004772          1         1
4        23.10   27.2000  426.0  704.50       0.004757          1         1

In [16]:
def clearning_files(file_name, class_name = 'Occupancy'):
    """
    This fuction is cleaing the data:
        - add new column week day
        - remove date and number column
        
    """
    
    file = '/Users/piyush2017/Code/2020_Data_Mining_Project_02/data_mining_2020_project_occupancy_detection/data/%s.csv'%file_name 
    df = pd.read_csv(file, skipinitialspace=True, na_values='?', keep_default_na=True, parse_dates=True)
    columns2remove = ['Number'] #eliminiamo perchè non ci servono
    df.drop(columns2remove, inplace=True, axis=1)
    res = prepare_dataset(df, class_name)
    df, feature_names, class_values, numeric_columns, rdf, real_feature_names, features_map = res
    df.to_csv('/Users/piyush2017/Code/2020_Data_Mining_Project_02/data_mining_2020_project_occupancy_detection/data/preprocess%s.csv'%file_name,
             index = False) # here index is false because we don't want the column for index
    
    return df

In [12]:
clearning_files('datatrainingcopy')

In [18]:
def to_scale_data(df, class_name = 'Occupancy' ):
    """
    This is used to make scale the data.
    """
    
    
    from sklearn.preprocessing import StandardScaler

    scaler = StandardScaler()

    # here I am coverting to np and scaling the data to same value

    X_scaled = scaler.fit_transform(df[['Temperature', 'Humidity', 'Light', 
                                        'CO2', 'HumidityRatio']].values)

    # Here changing it to pd for export
    df01 = pd.DataFrame(data= X_scaled, columns=['Temperature', 'Humidity', 'Light',
                                                 'CO2', 'HumidityRatio'])
    df01['Week_day'] = df.Week_day
    df01['Occupancy'] = df.Occupancy

    #df01.to_csv("scaled_datatest2copy.csv")
    df01.head()
    
    return df01